version: "3"

services:
#  app:
#    build: .
#    restart: always
#    ports:
#      - 3000:3000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro

