version: "3.8"

services:
  backend:
    build:
      context: ./server
    restart: always
    container_name: backend
    volumes:
     - ./:/usr/src/app
     - /usr/src/app/node_modules
    networks:
      - node_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network:
