version: "3"

services:
  app:
    build: .
    restart: always
    container_name: app


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro

