version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - 3000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro

