version: "3"

services:
  backend:
    build: .
    restart: always
    container_name: backend

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 3000:80
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d
      - ./nginx/configs/:/etc/nginx/sites-enabled/:ro

