version: "3.8"

services:
  backend:
    build:
      context: ./server
    restart: always
    container_name: backend
    ports:
      - 3000:3000

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    #  - 443:443

