query getEvent($slug: String!) {
    event(slug: $slug) {
        address
        booking_count
        charity
        description
        eventComments {
            content
            created_at
            parent
            author {
                name
                email
            }
            id
        }
        location
        poster
        start_time
        genre
    }
}
